DROP DATABASE IF EXISTS todo_db;

CREATE DATABASE todo_db;

USE todo_db;

CREATE TABLE items (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  text VARCHAR(255) NOT NULL,
  isDone BOOLEAN NOT NULL
);
